services:
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=nqM9Ykigd9e3cJnOpNhkJq54TmedyuoO
    ports:
        - "1433:1433"